import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import usersRouter from "./users";
import ridesRouter from "./rides";
import biddingRouter from "./bidding";
import driverRouter from "./driver";
import adminRouter from "./admin";
import adminExtendedRouter from "./admin-extended";
import settingsRouter from "./settings";
import mapsRouter from "./maps";
import placesRouter from "./places";
import messagesRouter from "./messages";
import safetyRouter from "./safety";
import withdrawalsRouter from "./withdrawals";
import paymentsRouter from "./payments";
import financeRouter from "./finance";
import couponsRouter from "./coupons";
import referralsRouter from "./referrals";
import notificationSoundsRouter from "./notification-sounds";
import siteRouter from "./site";
import currenciesRouter from "./currencies";
import driverPromotionsRouter from "./driverPromotions";
import queuedRidesRouter from "./queuedRides";
import destinationModeRouter from "./destinationMode";
import userSettingsRouter from "./user-settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(ridesRouter);
router.use(biddingRouter);
router.use(driverRouter);
router.use(adminRouter);
router.use(adminExtendedRouter);
router.use(settingsRouter);
router.use(mapsRouter);
router.use(placesRouter);
router.use(messagesRouter);
router.use(safetyRouter);
router.use(withdrawalsRouter);
router.use(paymentsRouter);
router.use(financeRouter);
router.use(couponsRouter);
router.use(referralsRouter);
router.use(notificationSoundsRouter);
router.use(siteRouter);
router.use(currenciesRouter);
router.use(driverPromotionsRouter);
router.use(queuedRidesRouter);
router.use(destinationModeRouter);
router.use(userSettingsRouter);

export default router;
